const FORCE_TEMPLATES = [{"id": "t_f_001", "type": "template", "category": "不動産登記", "title": "所有権保存登記", "body": "登記の目的　所有権保存\n\n原因　令和○年○月○日新築\n\n所有者　住所　氏名\n\n添付情報\n住所証明情報\n代理権限証明情報\n\n登録免許税　金○円", "level": 1, "knowledge": "所有権保存登記は、初めて所有権の登記をする手続。表題部所有者、相続人など申請適格者を確認する。"}, {"id": "t_f_002", "type": "template", "category": "不動産登記", "title": "所有権移転登記・売買", "body": "登記の目的　所有権移転\n\n原因　令和○年○月○日売買\n\n権利者　住所　氏名\n義務者　住所　氏名\n\n添付情報\n登記原因証明情報\n登記識別情報\n印鑑証明書\n住所証明情報\n代理権限証明情報\n\n登録免許税　金○円", "level": 1, "knowledge": "売買による所有権移転は、権利者・義務者の共同申請が原則。登記識別情報、印鑑証明書、住所証明情報の要否を整理する。"}, {"id": "t_f_003", "type": "template", "category": "不動産登記", "title": "相続による所有権移転登記", "body": "登記の目的　所有権移転\n\n原因　令和○年○月○日相続\n\n相続人　住所　氏名\n\n添付情報\n登記原因証明情報\n住所証明情報\n代理権限証明情報\n\n登録免許税　金○円", "level": 1, "knowledge": "相続登記では、被相続人の死亡日、相続人、戸籍一式、遺産分割協議書の要否、住所証明情報を確認する。"}, {"id": "t_f_004", "type": "template", "category": "不動産登記", "title": "抵当権設定登記", "body": "登記の目的　抵当権設定\n\n原因　令和○年○月○日金銭消費貸借同日設定\n\n債権額　金○円\n利息　年○％\n損害金　年○％\n債務者　住所　氏名\n抵当権者　住所　氏名\n設定者　住所　氏名\n\n添付情報\n登記原因証明情報\n登記識別情報\n印鑑証明書\n代理権限証明情報\n\n登録免許税　金○円", "level": 1, "knowledge": "抵当権設定では、債権額、利息、損害金、債務者、抵当権者、設定者を整理する。"}, {"id": "t_f_005", "type": "template", "category": "不動産登記", "title": "根抵当権設定登記", "body": "登記の目的　根抵当権設定\n\n原因　令和○年○月○日設定\n\n極度額　金○円\n債権の範囲　○○取引\n債務者　住所　氏名\n根抵当権者　住所　氏名\n設定者　住所　氏名\n\n添付情報\n登記原因証明情報\n登記識別情報\n印鑑証明書\n代理権限証明情報\n\n登録免許税　金○円", "level": 1, "knowledge": "根抵当権は、極度額、債権の範囲、債務者、根抵当権者を重点的に確認する。"}, {"id": "t_f_006", "type": "template", "category": "不動産登記", "title": "抵当権抹消登記", "body": "登記の目的　抵当権抹消\n\n原因　令和○年○月○日弁済\n\n権利者　住所　氏名\n義務者　住所　氏名\n\n添付情報\n登記原因証明情報\n登記識別情報\n代理権限証明情報\n\n登録免許税　金○円", "level": 1, "knowledge": "抵当権抹消では、登記原因、抹消すべき登記、登記識別情報、代理権限証明情報を確認する。"}, {"id": "t_c_001", "type": "template", "category": "商業登記", "title": "株式会社設立登記", "body": "登記の事由　株式会社設立\n\n登記すべき事項\n商号\n本店\n目的\n発行可能株式総数\n資本金の額\n役員に関する事項\n公告方法等\n\n課税標準金額　金○円\n登録免許税　金○円\n\n添付書類\n定款\n発起人決定書\n就任承諾書\n払込みを証する書面\n印鑑証明書\n委任状", "level": 1, "knowledge": "株式会社設立登記は、定款、発起人決定、役員就任、払込み、登録免許税を一連で整理する。"}, {"id": "t_c_002", "type": "template", "category": "商業登記", "title": "役員変更登記", "body": "登記の事由　取締役変更\n\n登記すべき事項\n令和○年○月○日次の者就任\n取締役　氏名\n\n登録免許税　金○円\n\n添付書類\n株主総会議事録\n取締役会議事録\n就任承諾書\n印鑑証明書\n委任状", "level": 1, "knowledge": "役員変更登記は、就任・辞任・任期満了・重任で添付書面が変わる。印鑑証明書の要否が頻出。"}, {"id": "t_c_003", "type": "template", "category": "商業登記", "title": "本店移転登記", "body": "登記の事由　本店移転\n\n登記すべき事項\n令和○年○月○日本店移転\n本店　○県○市○町○番○号\n\n登録免許税　金○円\n\n添付書類\n株主総会議事録\n取締役会議事録\n取締役決定書\n委任状", "level": 1, "knowledge": "本店移転は、管轄内移転か管轄外移転かで手続が変わる。定款変更の要否、決議機関を確認する。"}, {"id": "t_c_004", "type": "template", "category": "商業登記", "title": "目的変更登記", "body": "登記の事由　目的変更\n\n登記すべき事項\n目的\n1　○○\n2　前号に附帯関連する一切の事業\n\n登録免許税　金○円\n\n添付書類\n株主総会議事録\n委任状", "level": 1, "knowledge": "目的変更は定款変更事項。株主総会特別決議が必要。登記すべき事項の記載を正確に整理する。"}];
  function mergeTemplatesIntoStorage(){
    const keys = ["shihoAppDataV2","shihoUnifiedData"];
    keys.forEach(function(key){
      try {
        const raw = localStorage.getItem(key);
        let data = raw ? JSON.parse(raw) : null;
        if(!data || typeof data !== "object") return;
        if(!Array.isArray(data.templates)) data.templates = [];
        const existing = new Set(data.templates.map(t => t && (t.id || t.title)));
        FORCE_TEMPLATES.forEach(function(t){
          if(!existing.has(t.id) && !existing.has(t.title)) data.templates.push(t);
        });
        localStorage.setItem(key, JSON.stringify(data));
      } catch(e) {}
    });
  }
  mergeTemplatesIntoStorage();
  window.__FORCE_TEMPLATES__ = FORCE_TEMPLATES;
})();

const INITIAL_DATA = {"version": 2, "problems": [{"id": "p0001", "type": "problem", "subject": "民法", "topic": "留置権", "level": 1, "memo": "", "knowledge": "民法295条。要件：他人の物の占有、債権と物との牽連性、弁済期到来。優先弁済権はない。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}, {"id": "p0002", "type": "problem", "subject": "民法", "topic": "同時履行の抗弁権", "level": 1, "memo": "", "knowledge": "民法533条。双務契約上の対立債務。留置権との比較で占有不要。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}, {"id": "p0003", "type": "problem", "subject": "不動産登記法", "topic": "仮登記", "level": 1, "memo": "", "knowledge": "1号仮登記と2号仮登記の違い、順位保全効、登記原因を整理する。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}, {"id": "p0004", "type": "problem", "subject": "商業登記法", "topic": "役員変更登記", "level": 1, "memo": "", "knowledge": "就任・辞任・重任・任期満了で添付書面が変わる。印鑑証明書の要否が頻出。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}], "templates": [{"id": "t001", "type": "template", "category": "不動産登記", "title": "所有権保存登記", "body": "登記の目的　所有権保存\n原因　年月日新築\n所有者　住所　氏名\n添付情報　住所証明情報　代理権限証明情報\n登録免許税　金○円", "level": 1, "knowledge": "所有権保存登記は、初めて所有権の登記をする場面。申請適格を整理する。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}, {"id": "t002", "type": "template", "category": "不動産登記", "title": "所有権移転登記・売買", "body": "登記の目的　所有権移転\n原因　年月日売買\n権利者　住所　氏名\n義務者　住所　氏名\n添付情報　登記原因証明情報　登記識別情報　印鑑証明書　住所証明情報　代理権限証明情報\n登録免許税　金○円", "level": 1, "knowledge": "売買による所有権移転は共同申請。登記識別情報、印鑑証明書、住所証明情報を確認。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}, {"id": "t003", "type": "template", "category": "商業登記", "title": "株式会社設立登記", "body": "登記の事由　株式会社設立\n登記すべき事項　商号　本店　目的　発行可能株式総数　資本金の額　役員に関する事項等\n登録免許税　金○円\n添付書類　定款　発起人決定書　就任承諾書　払込み証明書　印鑑証明書　委任状", "level": 1, "knowledge": "設立登記は定款・発起人決定・役員就任・払込みを一連で整理する。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}, {"id": "t004", "type": "template", "category": "商業登記", "title": "役員変更登記", "body": "登記の事由　取締役変更\n登記すべき事項　年月日次の者就任　取締役　氏名\n登録免許税　金○円\n添付書類　株主総会議事録　就任承諾書　印鑑証明書　委任状", "level": 1, "knowledge": "役員変更は、就任・辞任・任期満了・重任で添付書面が変わる。", "mistakes": 0, "reviewCount": 0, "lastViewed": "", "lastReviewed": "", "createdAt": ""}], "comparisons": [{"id": "c001", "title": "留置権 vs 同時履行の抗弁権", "left": "留置権", "right": "同時履行の抗弁権", "points": [{"label": "根拠", "left": "民法295条", "right": "民法533条"}, {"label": "対象", "left": "他人の物の占有が必要", "right": "双務契約上の対立債務"}, {"label": "効力", "left": "物を留置できる", "right": "履行を拒絶できる"}, {"label": "注意", "left": "優先弁済権はない", "right": "占有は不要"}]}, {"id": "c002", "title": "抵当権 vs 根抵当権", "left": "抵当権", "right": "根抵当権", "points": [{"label": "被担保債権", "left": "特定債権", "right": "一定範囲の不特定債権"}, {"label": "極度額", "left": "不要", "right": "必要"}, {"label": "元本確定", "left": "問題になりにくい", "right": "重要論点"}, {"label": "登記", "left": "原因債権を意識", "right": "極度額・債権の範囲を意識"}]}], "settings": {"theme": "dark-gold"}};
